In [1]:
import numpy as np

In [30]:
size1=[int(i) for i in input("Enter size of matrix1:").split(" ")]
m1=[]
print("Enter elements into matrix1:")
for i in range(size1[0]):
    r=[]
    for j in range(size1[1]):
       r.append(int(input()))
    m1.append(r)
size2=[int(i) for i in input("Enter size of matrix2:").split(" ")]
m2=[]
print("Enter elements into matrix2:")
for i in range(size2[0]):
    r=[]
    for j in range(size2[1]):
       r.append(int(input()))
    m2.append(r)

Enter size of matrix1:3 3
Enter elements into matrix1:
4
5
7
8
1
2
9
6
3
Enter size of matrix2:3 3
Enter elements into matrix2:
8
5
2
9
6
3
1
4
7


In [31]:
x=np.array(m1)
y=np.array(m2)
print("1.",x,y,sep="\n")


1.
[[4 5 7]
 [8 1 2]
 [9 6 3]]
[[8 5 2]
 [9 6 3]
 [1 4 7]]


In [32]:
print("2.\n",np.dot(x,y))

2.
 [[ 84  78  72]
 [ 75  54  33]
 [129  93  57]]


In [33]:
print("3.",np.transpose(x),np.transpose(y),sep="\n\n")

3.

[[4 8 9]
 [5 1 6]
 [7 2 3]]

[[8 9 1]
 [5 6 4]
 [2 3 7]]


In [35]:
print("4.",np.trace(x),np.trace(y),sep="\n\n")

4.

8

21


In [43]:
print("5.",np.linalg.matrix_rank(x),np.linalg.matrix_rank(y),sep="\n  ")

5.
  3
  2


In [46]:
print("6.",np.linalg.det(x),np.linalg.det(y),sep="\n\t")

6.
	206.99999999999994
	-1.3322676295501874e-14


In [48]:
print("7.",np.linalg.inv(x),np.linalg.inv(y),sep="\n\t")

7.
	[[-0.04347826  0.13043478  0.01449275]
 [-0.02898551 -0.24637681  0.23188406]
 [ 0.1884058   0.10144928 -0.17391304]]
	[[-2.25179981e+15  2.02661983e+15 -2.25179981e+14]
 [ 4.50359963e+15 -4.05323966e+15  4.50359963e+14]
 [-2.25179981e+15  2.02661983e+15 -2.25179981e+14]]


In [49]:
print("8.",np.linalg.eig(x),np.linalg.eig(y),sep="\n\t")

8.
	(array([15.20765652+0.j        , -3.60382826+0.78992818j,
       -3.60382826-0.78992818j]), array([[ 0.6085836 +0.j        ,  0.45709788-0.13269663j,
         0.45709788+0.13269663j],
       [ 0.43600462+0.j        , -0.84833342+0.j        ,
        -0.84833342-0.j        ],
       [ 0.66296755+0.j        ,  0.12439916+0.19572527j,
         0.12439916-0.19572527j]]))
	(array([1.53218254e+01, 6.24500451e-16, 5.67817462e+00]), array([[-0.58835681, -0.40824829, -0.30025441],
       [-0.69891226,  0.81649658, -0.23078043],
       [-0.40664226, -0.40824829,  0.92552022]]))


In [5]:
print(dir(np.array([])))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [39]:
print(dir(np.linalg))

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'cholesky', 'cond', 'det', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


In [6]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp