In [1]:
import numpy as np

In [19]:
x=np.array([9,5,14,5])
y=np.array([2,9,7,5])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ True False  True False]
[ True False  True  True]
[False  True False False]
[False  True False  True]


In [20]:
even=np.arange(30,70,2)
print(even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [24]:
i=np.identity(3,int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [38]:
a=np.arange(0,21)
print(a)
print("After change")
a[ (a>=9) & (a<=15) ]*=-1
print(a)

# a=[-i if i>=9 and i=<15 else i for i in a ]
# a=np.array(a)
# print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After change
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
