In [2]:
import numpy as np

In [19]:
x=np.array([9,5,14,5])
y=np.array([2,9,7,5])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ True False  True False]
[ True False  True  True]
[False  True False False]
[False  True False  True]


In [20]:
even=np.arange(30,71,2)
print(even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [24]:
i=np.identity(3,int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [50]:
a=np.arange(0,21)
print(a)
print("After change")
a[ (a>=9) & (a<=15) ]*=-1
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After change
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [21]:
a=np.zeros((5,5),int)
print(a)
dir(a)
np.fill_diagonal(a,[1,2,3,4,5])
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [31]:
a=np.arange(20,230,18)
a=a.reshape(4,3)
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

[[ 20  38  56]
 [ 74  92 110]
 [128 146 164]
 [182 200 218]]
1428
[404 476 548]
[114 276 438 600]


In [41]:
a=np.random.randint(4,19,(4,3))
np.savetxt("array.txt",a)
print(a)
b=np.loadtxt("array.txt")
b

[[17 17  7]
 [15 12 13]
 [ 5  4  5]
 [ 4 13  5]]


array([[17., 17.,  7.],
       [15., 12., 13.],
       [ 5.,  4.,  5.],
       [ 4., 13.,  5.]])

In [54]:
a=np.array([1,2,9])
b=np.array([1,2,3])
np.all(a==b)

False

In [48]:
a=np.random.randint(4,19,(4,4))
print(a)
b=np.copy(a)
b[[0,-1]]=b[[-1,0]]
b

[[16  7 16 18]
 [14 18 10  6]
 [ 9  6 13 12]
 [ 7 14 12  7]]


array([[ 7, 14, 12,  7],
       [14, 18, 10,  6],
       [ 9,  6, 13, 12],
       [16,  7, 16, 18]])

In [49]:
a=np.array([1,5,6,9])
b=np.array([4,6,7,3])
np.multiply(a,b)

array([ 4, 30, 42, 27])

In [45]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [53]:
a=np.array([[1,5],[2,4]])
b=np.array([[4,6,7,3],[7,74,67,71]])
np.matmul(a,b)

array([[ 39, 376, 342, 358],
       [ 36, 308, 282, 290]])